package week13_labs;

import java.util.ArrayList;
import java.util.Random;


public class Dice implements week13_labs  {

      
        private int dice;
        private ArrayList<Integer> abc;
        public static final Random rand = new Random();


        public Dice(int d) {

                dice = d;

                abc = new ArrayList<Integer>();

                 }

        public Dice() {

                   this(1);

          }


        
        
         public int getGeneratedRandomNumber() throws Exception {

                if ( abc.size() > 3)
                {
                        throw new Exception();
                }

                 int number = rand.nextInt(6 * dice) + 1;

                 this.abc.add(number);

                  return number;

                  }
}




package week13_labs;

public class test_program {

        public static void main(String[] args) throws Exception {


                Dice myDice = new Dice();



                try 
                {
                        System.out.println("Method throwException called");
                        myDice.getGeneratedRandomNumber();
                        myDice.getGeneratedRandomNumber();
                        myDice.getGeneratedRandomNumber();
                } 
                catch ( Exception exception ) 
                {
                        System.err.println("Exception catched");
                } 


                try 
                {
                        System.out.println("Method throwException called");
                        myDice.getGeneratedRandomNumber();
                        myDice.getGeneratedRandomNumber();
                        myDice.getGeneratedRandomNumber();
                        myDice.getGeneratedRandomNumber();

                }
                catch ( Exception exception ) 
                {
                        System.err.println("Exception catched");
                }

                finally 
                {
                        System.err.println("Finally executed in throwException");
                } 
                }



}
